# name: 'dataco'
# version: '1.0.0'
# config-version: 2
# profile: 'dataco'
# model-paths: ["models"]
# target-path: "target"
# clean-targets:
#   - "target"
#   - "dbt_packages"
# models:
#   dataco:
#     materialized: table


name: 'dataco_project'
version: '1.0.0'
config-version: 2
profile: 'default'
model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
models:
  dataco_project:
    materialized: table